### ISSUE TITLE
file:// URLs from relative paths still don't work

### ISSUE THREAD

**Issue by jiatern** [gildas-lormeau/single-file-cli#106]
Hi, previously there was a commit https://github.com/gildas-lormeau/single-file-cli/commit/b3cec4d5ce1828e6f65b93ae09013e34603f74e9 to fix input from pages opened from the filesystem. I didn't test it back then because I was still using v1.x of single-file. Now that v2 works for my use case, I realized that relative filepath still doesn't work.

Version: 2.0.45
OS: Debian 12

When I run `$ single-file input.html output.html`, I get the following error:
```
Unreachable URL: file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/input.html URL: file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/input.html
Stack: Error: Unreachable URL: file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/input.html
    at Connection.onFrameNavigated (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/cdp-client.js:306:15)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at Connection.dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at Connection.#onMessage (https://jsr.io/@simple-cdp/simple-cdp/1.8.5/mod.js:205:18)
    at WebSocket.<anonymous> (https://jsr.io/@simple-cdp/simple-cdp/1.8.5/mod.js:168:83)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
```

But if I specify full path with `file:///` structure e.g.
`$ single-file "file:///home/user/input.html" output.html`, it works.

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce and hopefully fix the issue. I've just published the new version with the fix.
