### ISSUE TITLE
Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed

### ISSUE THREAD

**Issue by YenForYang** [gildas-lormeau/single-file-cli#50]
```
Stack: ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (C:\Users\Richard\single-file-cli\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:49:14)
    at new Callback (C:\Users\Richard\single-file-cli\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:53:16)
    at CallbackRegistry.create (C:\Users\Richard\single-file-cli\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:93:26)
    at Connection._rawSend (C:\Users\Richard\single-file-cli\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:207:26)
    at CDPSessionImpl.send (C:\Users\Richard\single-file-cli\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:416:33)
    at #evaluate (C:\Users\Richard\single-file-cli\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:234:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Richard\single-file-cli\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:149:16)
    at async getPageData (C:\Users\Richard\single-file-cli\back-ends\puppeteer.js:153:10)
    at async exports.getPageData (C:\Users\Richard\single-file-cli\back-ends\puppeteer.js:56:10)
```

`node -v` is `v20.5.1`. Can't share the webpage unfortunately. Used the latest version of the project: v1.0.65.

Notable options used (to fix the use case here: https://github.com/gildas-lormeau/SingleFile/issues/105):
```
--remove-hidden-elements=false
--remove-unused-styles=false
--block-scripts=false
```
Used Google Chrome as the browser.
Only tested once in browser with the extension; unfortunately the whole browser crashed or force quit (when it was nearing completion) with the above settings and I haven't gotten the chance to retry.

**Comment by gildas-lormeau** [comment]
I'm closing this bug because the version 2.x does not rely on puppeteer anymore.
