### ISSUE TITLE
yandex-alpha?

### ISSUE THREAD

**Issue by emental2** [gildas-lormeau/single-file-cli#69]
On Ubuntu 22.04.4 LTS, downloaded single-file-x86_64-linux from https://github.com/gildas-lormeau/single-file-cli. When I try to run it, I get a very improbable message: the program asks for yandex-alpha! What happens?

user@user-desktop:~/Deskpiles-local$ ./single-file-x86_64-linux  dn.se ./gurka 
error: Uncaught (in promise) NotFound: Failed to spawn '/usr/bin/yandex-alpha': No such file or directory (os error 2)
    at spawnChildInner (ext:runtime/40_process.js:185:17)
    at spawnChild (ext:runtime/40_process.js:206:10)
    at Command.spawn (ext:runtime/40_process.js:474:12)
    at launchBrowser (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/browser.js:63:25)
    at eventLoopTick (ext:core/01_core.js:169:7)
    at async launchBrowser (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/browser.js:67:5)
    at async launchBrowser (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/browser.js:67:5)
    at async launchBrowser (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/browser.js:67:5)
    at async launchBrowser (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/browser.js:67:5)
    at async launchBrowser (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/browser.js:67:5)
user@user-desktop:~/Deskpiles-local$

**Comment by gildas-lormeau** [comment]
This happens if the program cannot find a Chromium-based browser on your system. Do you have a browser based on Chromium on your machine?
