### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'content') at capturePage

### ISSUE THREAD

**Issue by sissbruecker** [gildas-lormeau/single-file-cli#77]
Trying to save a copy of https://www.hightidestoredtla.shop/products/bullet-ballpoint-pen-light?variant=38087018184895 results in the following error:
```
Cannot read properties of undefined (reading 'content') URL: https://www.hightidestoredtla.shop/products/bullet-ballpoint-pen-light?variant=38087018184895
Stack: TypeError: Cannot read properties of undefined (reading 'content')
    at capturePage (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-cli-api.js:261:17)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async runNextTask (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-cli-api.js:164:20)
    at async Promise.all (index 0)
    at async capture (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-cli-api.js:115:2)
    at async run (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-launcher.js:82:3)
    at async file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file:5:1
```

Reproduction using Node v20.9.0:
```
npm i -g single-file-cli
single-file "https://www.hightidestoredtla.shop/products/bullet-ballpoint-pen-light?variant=38087018184895" test.html
```

Or the Deno standalone build:
```
./single-file-aarch64-apple-darwin "https://www.hightidestoredtla.shop/products/bullet-ballpoint-pen-light?variant=38087018184895" test.html
```

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce and fix the issue. The next version will include the fix.

**Comment by sissbruecker** [comment]
Great, thanks!

**Comment by gildas-lormeau** [comment]
You're welcome, the new version is available for download.
