### ISSUE TITLE
TypeError: Windows only supports ctrl-c (SIGINT) and ctrl-break (SIGBREAK)

### ISSUE THREAD

**Issue by SoroGin** [gildas-lormeau/single-file-cli#84]
I get the following running single-file.exe 2.0.30 on Windows 11

```
error: Uncaught (in promise) TypeError: Windows only supports ctrl-c (SIGINT) and ctrl-break (SIGBREAK).
    at bindSignal (ext:runtime/40_signals.js:14:10)
    at Object.addSignalListener (ext:runtime/40_signals.js:54:19)
    at addSignalListener (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/deno-polyfill.js:213:8)
    at file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-launcher.js:31:1
```

It happens immediately, and just running in powershell with no other options like the following:

```
.\single-file.exe "https://www.google.com/"
```

**Comment by gildas-lormeau** [comment]
Thank you, I published the version 2.0.31 which should fix the error.
